# Generated by Django 2.2.5 on 2020-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall', models.CharField(default='', max_length=256)),
                ('product', models.CharField(default='', max_length=256)),
                ('product_category', models.CharField(default='', max_length=256)),
                ('shop_name', models.CharField(default='', max_length=256)),
                ('shop_address', models.CharField(default='', max_length=256)),
                ('price', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
