# Generated by Django 3.0.3 on 2020-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200421_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='shop_address',
            field=models.CharField(blank=True, default='address', max_length=256),
        ),
        migrations.AlterField(
            model_name='entry',
            name='shop_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
