# Generated by Django 3.0.3 on 2020-04-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20200422_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='shop_address',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
